name: Java Build

# Trigger workflow on push or pull request for specific branches
on:
  push:
    branches:
      - master
      - Calculator
      - grade
  pull_request:
    branches:
      - master
      - Calculator
      - grade

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 3️⃣ Compile Java files
      - name: Compile Java
        run: |
          mkdir -p out
          find . -name "*.java" > sources.txt
          javac -d out @sources.txt

      # 4️⃣ List compiled files (optional)
      - name: List compiled classes
        run: ls -R out
